pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
    }
    plugins {
        id 'org.jetbrains.kotlin.jvm' version '2.0.0'
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'Machine-Max'

def sparkCoreDir = file("${spark_core_dir}") // 此处修改为Spark-Core源码所在目录
if (sparkCoreDir.exists()) { // 首选同目录下Spark-Core源码作为依赖
    includeBuild(sparkCoreDir) {
        dependencySubstitution {
            substitute(module("io.github.solarmoonqaq:spark-core-${mod_loader}"))
                    .using(project(":"))
        }
    }
} else { // 若不存在，则使用发布的/本地jar作为依赖
    println("[Machine-Max] Spark-Core not found, using published/local jar")
}

def ballisticsFrameworkDir = file("${ballistics_framework_dir}") // 弹道框架源码目录
if (ballisticsFrameworkDir.exists()) { // 首选同目录下弹道框架源码作为依赖
    includeBuild(ballisticsFrameworkDir) {
        dependencySubstitution {
            substitute(module("io.github.sweetzonzi:ballistics_framework-${minecraft_version}"))
                    .using(project(":"))
        }
    }
} else { // 若不存在，则使用发布的/本地jar作为依赖
    println("[Machine-Max] BallisticsFramework not found, using published/local jar")
}
