modLoader="kotlinforforge"

loaderVersion="${loader_version_range}"

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="${mod_license}"

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="${mod_id}" #mandatory

# The version number of the mod
version="${mod_version}" #mandatory

# A display subpart for the mod
displayName="${mod_name}" #mandatory

# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

# A file subpart (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional
authors="${mod_authors}"
credits="${mod_credits}"
description='''${mod_description}'''
[[mixins]]
config="${mod_id}.mixins.json"
#[[mixins]]
#config="${mod_id}.native.mixins.json"
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="kotlinforforge"
    type="required"
    versionRange="[${kotlinforforge_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="spark_core"
    type="required"
    versionRange="[${spark_core_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ballistics_framework"
    type="required"
    versionRange="[${ballistics_framework_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="apricityui"
    type="required"
    versionRange="[1.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jade"
    type="optional"
    versionRange="[15,16)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="jei"
    type="optional"
    versionRange="[19,20)"
    ordering="AFTER"
    side="CLIENT"
